### ISSUE TITLE
Counter type metrics displayed wrong as decimal values

### ISSUE THREAD

**Issue by shvetsovdm** [yabeda-rb/yabeda-datadog#17]
It turns out that count metrics in **Datadog**, in reality, are rate metrics over flush interval, 10 seconds by default.

[source](https://docs.datadoghq.com/developers/metrics/#submission-types-and-datadog-in-app-types) (note: yabeda-datadog using dogstatsd)

**yabeda-datadog** sends metrics as rate type and after the gem registration methods are called this metrics metadata updated and their type becomes counters. Counters have no flush interval and Datadog graphing show it as raw values which is divided by the flush interval which is 10. That why count type metrics from **yabeda-datadog** displayed as decimal values.

**Comment by shvetsovdm** [comment]
@palkan can you try this commit/branch https://github.com/yabeda-rb/yabeda-datadog/commit/f391ac26ec72e6f0622c6d171ba02b549f4f6ec0 it should solve the issue

**Comment by palkan** [comment]
@shvetsovdm yep, solved) let's release it!

**Comment by shvetsovdm** [comment]
@palkan 0.3.3 released

**Comment by palkan** [comment]
Thanks!

**Comment by shvetsovdm** [comment]
Sorry, in a hurry made a release with broken Gemfile.lock, please use 0.3.4

**Comment by palkan** [comment]
It's not a problem. The `.lock` file doesn't affect the gem's functionality.

Btw, you shouldn't add `Gemfile.lock` to the gem's repo at all to run tests against the spec (from `.gemspec`) and not against the locked versions.
